### PR TITLE
Force lowercase in get_project_name

### PR DESCRIPTION
**Pull request by joshmoore**
see: https://github.com/ome/rOMERO-gateway/pull/41

Propose as a quick v0.3.2

/cc @sbesson @jburel @dominikl

### CODE REVIEW

**Comment by dominikl** [comment]
That's great, thanks @joshmoore !

**Comment by sbesson** [comment]
@dominikl have you tested it on https://github.com/ome/rOMERO-gateway/pull/41 (by temporarily cloning this branch rather than the upstream)? Once validated, I think this should be good to merge unless there is a chance this might negatively impact another consumer of `omero-test-infra`.

**Comment by dominikl** [comment]
Works, good to merge! 👍

**Comment by joshmoore** [comment]
Tag pushed.

**Pull request merged**
