### PR TITLE
Minor fix

### PR DESCRIPTION
**Pull request by jburel**
Nothing to test

### CODE REVIEW

**Comment by joshmoore** [comment]
Is there ever a case where having _extra_ trailing slashes is bad? Otherwise, it seems safer to err on the side of having them, no?

**Comment by jburel** [comment]
I don't think so I found it strange when looking at the output of a travis build
I can rollback.

**Comment by mtbc** [comment]
Yeah, the eye-catching strangeness alone is already a cost and not having them ensures the script still works when they're omitted in being explicitly configured to be something else.

**Comment by joshmoore** [comment]
@mtbc : fair enough, thanks.

**Pull request merged**
