### PR TITLE
Expose PLUGIN environment variable

### PR DESCRIPTION
**Pull request by sbesson**
See https://github.com/ome/omero-metadata/pull/2

By default the `cli-build` guesses the name of the plugin from the repository name i.e. `omero-cli-<PLUGIN>`. If the repository name does not match this scheme, a `PLUGIN` variable allows to override the guess.

When using omero-test-infra with Travis, the `PLUGIN` variable is not propagated through the stack leading to incorrect guess - see https://travis-ci.org/ome/omero-metadata/builds/402142739. This PR makes the necessary changes to expose and propagate the value of `PLUGIN`

### CODE REVIEW

**Comment by dominikl** [comment]
This basically is tested by https://travis-ci.org/ome/omero-metadata/builds/409897298 , isn't it?
In that case, looks fine, good to merge 👍

**Comment by sbesson** [comment]
Yes generally `omero-metadata` is the first official example of CLI plugin which is not named `omero-cli-XXX` and needs this logic to be tested via `omero-test-infra`

**Comment by sbesson** [comment]
Thanks @joshmoore and completely agreed on the importance of the control build. I used `omero-cli-render` - see https://travis-ci.org/sbesson/omero-cli-render/builds/410232363 for the successful execution. Proposing to release as v0.3.5 if no veto.

**Comment by joshmoore** [comment]
Travis output looks good. :+1: for 0.3.5

**Pull request merged**
